const common = {
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    borderRadius: {
        sm: 6,
        md: 12,
        lg: 16,
        xl: 24,
        round: 9999,
    },
    typography: {
        h1: { fontSize: 32, fontWeight: '800', lineHeight: 40, letterSpacing: -0.5 },
        h2: { fontSize: 24, fontWeight: '700', lineHeight: 32, letterSpacing: -0.25 },
        h3: { fontSize: 20, fontWeight: '600', lineHeight: 28 },
        subtitle: { fontSize: 18, fontWeight: '500', lineHeight: 26 },
        body: { fontSize: 16, fontWeight: '400', lineHeight: 24 },
        caption: { fontSize: 14, fontWeight: '400', lineHeight: 20 },
        button: { fontSize: 16, fontWeight: '600', lineHeight: 24, letterSpacing: 0.5 },
    },
    shadows: {
        none: {
            shadowColor: 'transparent',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0,
            shadowRadius: 0,
            elevation: 0,
        },
        sm: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.2,
            shadowRadius: 1.41,
            elevation: 2,
        },
        md: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        lg: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.30,
            shadowRadius: 4.65,
            elevation: 8,
        },
    },
};

export const lightTheme = {
    ...common,
    colors: {
        primary: '#6366f1',
        primaryDark: '#4338ca',
        primaryLight: '#818cf8',
        secondary: '#06b6d4',
        accent: '#f472b6',
        background: '#f8fafc',
        surface: '#ffffff',
        surfaceHighlight: '#f1f5f9',
        modal: '#ffffff',
        textPrimary: '#0f172a',
        textSecondary: '#475569',
        textInverse: '#ffffff',
        textDisabled: '#94a3b8',
        success: '#10b981',
        error: '#ef4444',
        warning: '#f59e0b',
        info: '#3b82f6',
        border: '#e2e8f0',
        placeholder: '#94a3b8',
        backdrop: 'rgba(0, 0, 0, 0.3)',
    },
};

export const darkTheme = {
    ...common,
    colors: {
        primary: '#818cf8',
        primaryDark: '#6366f1',
        primaryLight: '#a5b4fc',
        secondary: '#22d3ee',
        accent: '#f472b6',
        background: '#0f172a',
        surface: '#1e293b',
        surfaceHighlight: '#334155',
        modal: '#1e293b',
        textPrimary: '#f8fafc',
        textSecondary: '#94a3b8',
        textInverse: '#ffffff',
        textDisabled: '#475569',
        success: '#10b981',
        error: '#ef4444',
        warning: '#f59e0b',
        info: '#3b82f6',
        border: '#334155',
        placeholder: '#64748b',
        backdrop: 'rgba(0, 0, 0, 0.6)',
    },
};

export const theme = darkTheme; // Default for backward compatibility during transition
